tile_dict = {
    0: ((0, 0), "tráva roh vlevo nahoře"),
    1: ((1, 0), "tráva nahoře hrana"),
    2: ((2, 0), "tráva roh vpravo nahoře"),
    3: ((0, 2), "tráva hrana vlevo"),
    4: ((1, 2), "tráva hrana dole"),
    5: ((2, 2), "tráva roh vpravo dole"),
    6: ((0, 3), "dům roh vlevo nahoře"),
    7: ((1, 3), "dům horní hrana"),
    8: ((2, 3), "dům roh vpravo nahoře"),
    9: ((0, 4), "dům levá strana"),
    10: ((1, 4), "dům střed"),
    11: ((2, 4), "dům pravá strana"),
    12: ((0, 5), "dům roh vlevo dole"),
    13: ((1, 5), "dům dolní hrana"),
    14: ((2, 5), "dům roh vpravo dole"),
    15: ((7, 0), "silnice roh vlevo nahoře"),
    16: ((8, 0), "silnice horní hrana"),
    17: ((9, 0), "silnice roh vpravo nahoře"),
    18: ((7, 1), "silnice levá strana"),
    19: ((8, 1), "silnice střed"),
    20: ((9, 1), "silnice pravá strana"),
    21: ((7, 2), "silnice roh vlevo dole"),
    22: ((8, 2), "silnice dolní hrana"),
    23: ((9, 2), "silnice roh vpravo dole"),
}
